services:
  app:
    build:
      context: .
    ports:
      - '${PORT:-8000}:8000'
    develop:
      watch:
        - action: rebuild
          path: .
    working_dir: /usr/src/app
    deploy:
      resources:
        limits:
          memory: 512m
