services:
  app:
    build:
      context: .
    ports:
      - '${PORT:-8000}:8000'
    volumes:
      - ./workspaces/server/dist/images/:/usr/src/app/workspaces/server/dist/images/
    working_dir: /usr/src/app
