services:
  app:
    build:
      context: .
    ports:
      - '${PORT:-8000}:8000'
    volumes:
      - type: bind
        source: ./workspaces/server/dist/images/
        target: /usr/src/app/workspaces/server/dist/images/
    working_dir: /usr/src/app
