services:
  app:
    build:
      context: .
    ports:
      - '${PORT:-8000}:8000'
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - node_modules/
            - .git/
        - action: rebuild
          path: package.json
    working_dir: /usr/src/app
    deploy:
      resources:
        limits:
          memory: 512m
